version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: update/dependencies
  labels:
  - dependencies
  - java
  ignore:
  - dependency-name: org.springframework.boot
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: com.gradle.build-scan
    versions:
    - 3.5.1
    - 3.5.2
    - "3.6"
