language: java

dist: xenial
jdk: openjdk11
install: true
sudo: required

before_install:
  - nvm install node 12.6.0
  - npm install -g @angular/cli

script:
  # Build
  - ./gradlew assemble
  - cd src/main/webapp
  # ng Unit tests
  - npm -f i
  - ng build --prod
  #- npm test
  # ng End2End tests
  #- npm run webdriver-update
  #- npm run webdriver-start
  # Disable E2E for now in CI
  #- npm run ci-e2e
  - cd ../../../
  # Java tests
  - ./gradlew test

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/src/main/webapp/node_modules
